[colors]
background       = '#191724'
black            = '#e0def4'
blue             = '#31748f'
cursor           = '#59546d'
cyan             = '#6e6a86'
foreground       = '#e0def4'
green            = '#9ccfd8'
magenta          = '#ebbcba'
red              = '#ebbcba'
tabs             = '#908caa'
tabs-active      = '#c4a7e7'
white            = '#e0def4'
yellow           = '#f6c177'
